---
# This playbook deploys a simple standalone Tomcat 7 server.

- hosts: AWS
  remote_user: ec2-user
  become: yes
  become_method: sudo
 # vars:
 #    ansible_python_interpreter: "/usr/bin/python"
 #    ansible_connection=local
  roles:
    - tomcat

